repos:
  - repo: local
    hooks:
      - id: hatch-style-fix
        name: Hatch Python style fixes
        entry: hatch run style:fix
        language: system
        pass_filenames: false
        files: ^(mkdocs|docs)/
      - id: hatch-spelling
        name: Hatch spelling check
        entry: hatch run lint:spelling
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^mkdocs/(contrib|themes)/
      - id: end-of-file-fixer
        exclude: ^mkdocs/(contrib|themes)/
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
