repos:
  - repo: local
    hooks:
      - id: hatch-style
        name: Hatch Python style
        entry: hatch run style:check
        language: system
        always_run: true
        pass_filenames: false
      - id: hatch-style-fix
        name: Hatch Python style fixes
        entry: hatch run style:fix
        language: system
        always_run: true
        pass_filenames: false
        stages: [manual]
      - id: hatch-types
        name: Hatch type check
        entry: hatch run types:check
        language: system
        always_run: true
        pass_filenames: false
      - id: hatch-project-lint
        name: Hatch project lint
        entry: hatch run lint:check
        language: system
        always_run: true
        pass_filenames: false
