name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 6'
  workflow_dispatch:

jobs:
  test-smoke:
    name: Smoke tests (${{ matrix.os }}, ${{ matrix.python-version }})
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: '3.8'
            test-script: test:test
          - os: ubuntu-latest
            python-version: '3.14'
            test-script: test:with-coverage
            upload-coverage: true
          - os: ubuntu-latest
            python-version: pypy-3.9-v7.x
            py: pypy3
            test-script: test:test
          - os: macos-latest
            python-version: '3.14'
            test-script: test:test
          - os: windows-latest
            python-version: '3.14'
            test-script: test:test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade hatch
      - name: Run tests
        run: |
          hatch run +py=${{ matrix.py || matrix.python-version }} ${{ matrix.test-script }}
      - name: Run integration tests
        run: |
          hatch run +py=${{ matrix.py || matrix.python-version }} integration:test
        shell: bash
      - name: Upload Codecov Results
        if: success() && matrix.upload-coverage
        uses: codecov/codecov-action@v6
        with:
          file: ./coverage.xml
          flags: unittests
          name: smoke/${{ matrix.os }}/${{ matrix.python-version }}
          fail_ci_if_error: false

  test-full:
    name: Full tests (ubuntu, ${{ matrix.python-version }})
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '3.8'
          - python-version: '3.9'
          - python-version: '3.10'
          - python-version: '3.11'
          - python-version: '3.12'
          - python-version: '3.13'
          - python-version: '3.14'
          - python-version: pypy-3.9-v7.x
            py: pypy3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade hatch
      - name: Run tests
        run: |
          hatch run +py=${{ matrix.py || matrix.python-version }} test:test
      - name: Run integration tests
        run: |
          hatch run +py=${{ matrix.py || matrix.python-version }} integration:test
        shell: bash

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade hatch pre-commit
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Run repository checks
        if: always()
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Check with mypy
        if: always()
        run: hatch run types:check

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -U build
      - name: Build package
        run: python -m build
      - name: Check packaged files
        shell: bash -e -x {0}
        run: |
          expected_wheel=(-emkdocs/{templates/sitemap.xml,config/base.py,py.typed,contrib/search/lunr-language/lunr.nl.js,themes/{mkdocs,readthedocs}/{base.html,locales/{de,es}/LC_MESSAGES/messages.mo}})
          expected_sdist=("${expected_wheel[@]}" -e{pyproject.toml,hatch_build.py})
          test "$(tar -ztf dist/mkdocs_ng-*.tar.gz | grep -F "${expected_sdist[@]}" | tee /dev/stderr | wc -l)" -eq "${#expected_sdist[@]}"
          test "$(unzip -l dist/mkdocs_ng-*any.whl | grep -F "${expected_wheel[@]}" | tee /dev/stderr | wc -l)" -eq "${#expected_wheel[@]}"
