name: Docs
on:
  push:
    branches:
      'main'
  pull_request:
    branches:
      'main'
  schedule:
    - cron: '0 6 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install hatch
      - name: Build site
        run: hatch run docs:build

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download source
        uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install hatch
      - name: Deploy to GitHub Pages
        run: hatch run docs:deploy
